version: '3.7'

services:
  # app:
  #   container_name: app
  #   image: my-login-app
  #   ports:
  #     - 3001:3001
  #   depends_on:
  #     - psql
  #   networks:
  #     - my_network

  psql:
    container_name: db
    image: postgres:15
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: